name: Production Deploy
on:
  push:
    branches: [stable]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: npm install
        run: npm install

      - name: Build minified
        run: hugo --environment production --minify

      - name: FTP Deploy to production domain
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.production_ftp_hostname }}
          username: ${{ secrets.production_ftp_username }}
          password: ${{ secrets.production_ftp_password }}
          dry-run: false
          local-dir: ./public/
          server-dir: ${{ secrets.production_server_folder }}
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
